import { v4 as uuidv4 } from 'uuid';

export const shapesObj = {
  rect: {
    type: "rect",
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    width: 50,
    height: 50,
    fill: '#cd2424',
    stroke: "#8c4b4b",
    strokeWidth: 0,
    cornerRadius: 0,
    id: uuidv4(),
  },
  circle: {
    type: "circle",
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    width: 50,
    height: 50,
    fill: '#cd2424',
    stroke: "#8c4b4b",
    strokeWidth: 0,
    cornerRadius: 0,
    id: uuidv4(),
  },
  star: {
    type: "star",
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    numPoints: 5,
    innerRadius: 10,
    outerRadius: 10,
    width: 50,
    height: 50,
    fill: '#cd2424',
    stroke: "#8c4b4b",
    strokeWidth: 0,
    id: uuidv4(),
  },
  text: {
    type: "text",
    fontSize: 24,
    fontFamily: "Roboto",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Some text",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  image: {
    type: "image",
    url: "",
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    id: uuidv4(),
  }
}