import { v4 as uuidv4 } from 'uuid';

export const textsArr = [
  {
    type: "text",
    fontSize: 50,
    fontFamily: "Roboto",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Title",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  {
    type: "text",
    fontSize: 24,
    fontFamily: "Roboto",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Description",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  {
    type: "text",
    fontSize: 64,
    fontFamily: "Tiny5",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Pixels",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  {
    type: "text",
    fontSize: 24,
    fontFamily: "Open Sans",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Elegant",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  {
    type: "text",
    fontSize: 16,
    fontFamily: "Anton",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Subtitle",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  {
    type: "text",
    fontSize: 32,
    fontFamily: "Ubuntu",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Programmer",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  {
    type: "text",
    fontSize: 44,
    fontFamily: "Josefin Sans",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Josefin Jackson",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
  {
    type: "text",
    fontSize: 36,
    fontFamily: "Domine",
    fill: '#cd2424',
    width: 200,
    x: (window.innerWidth - 500) / 2,
    y: window.innerHeight / 2,
    text: "Domino",
    opacity: 100,
    fontStyle: "",
    textDecoration: "",
    align: "center",
    id: uuidv4(),
  },
]